sudo: required
dist: trusty

language: cpp

git:
    depth: 3

branches:
    only:
    - master
    - build-system-trial

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      language: cpp
      sudo: required
      cache:
        apt: true
        directories:
          - ./external/Catch/src/Catch-External
      before_install:
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - cat /etc/apt/sources.list
        - sudo apt-get update -qq
        - sudo apt-get install build-essential g++-4.8 -y
        - sudo apt-get install cmake -y
        - sudo apt-get install libboost-filesystem-dev libboost-system-dev -y 
        - sudo apt-get install lib3ds-dev -y
        - sudo apt-get install libcgal-qt5-dev libcgal -y
      script:
        - mkdir build && mkdir build/trusty && cd build/trusty
        - cmake -DCGAL_DONT_OVERRIDE_CMAKE_FLAGS=ON ../..
        - make -j4 all
        - test_exec -a
        

    - os: linux
      services:
        - docker
      script:
        - docker build .


    - os: osx
      osx_image: xcode8
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
          - ./external/Catch/src/Catch-External
      compiler: clang
      before_install:
        - brew update
        - brew outdated boost || brew upgrade boost
        - brew outdated cgal || brew upgrade cgal
        - brew install lib3ds
        - mkdir build
        - mkdir build/darwin
      install:
        - cd build/darwin
        - cmake -DCGAL_DONT_OVERRIDE_CMAKE_FLAGS=ON ../..
      script:
        - make -j4 all
        - ./test_exec -a
