sudo: required
dist: trusty

language: cpp

git:
    depth: 3

branches:
    only:
    - master
    - osx-travis

matrix:
  include:
    - os: linux

    - os: osx
      osx_image: xcode8
      compiler: clang

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew upgrade; brew install boost cgal lib3ds; mkdir build; mkdir build/darwin; fi

install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake ../..; fi

services:
    - docker

script:
    - docker build .
