sudo: required
dist: trusty

language: cpp

git:
    depth: 3

branches:
    only:
    - master
    - build-system-trial

matrix:
  include:
    - os: linux
      services:
        - docker
      script:
        - docker build .


    - os: osx
      osx_image: xcode8
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
          - ./external
          - $HOME/3rdParty
      compiler: clang
      before_install:
        - brew update
        - brew outdated boost || brew upgrade boost
        - brew outdated cgal || brew upgrade cgal
        - brew outdated qt5 || brew upgrade qt5
        - brew outdated wget || brew upgrade wget
        - brew install lib3ds
        - brew install tinyxml2
        - mkdir 3rdParty && cd 3rdParty
        - mkdir GDAL && cd GDAL
        - wget http://www.kyngchaos.com/files/software/frameworks/GDAL_Complete-2.1.dmg
        - sudo hdiutil attach GDAL_Complete-2.1.dmg
        - sudo installer -package "/Volumes/GDAL Complete/GDAL Complete.pkg" -target /
        - cd .. && mkdir Imagine++ && cd Imagine++
        - wget http://imagine.enpc.fr/~monasse/Imagine++/downloads/Imagine++-4.3.1-Darwin-i386.pkg
        - sudo installer -package Imagine++-4.3.1-Darwin-i386.pkg /
        - cd $HOME
      install:
        - mkdir build && mkdir build/darwin && cd build/darwin
        - cmake -DCGAL_DONT_OVERRIDE_CMAKE_FLAGS=ON ../..
      script:
        - make -j4 all
        - ./tests -a
        - rm *.off *.3ds *.gml *.xsd *.geotiff
