sudo: required
dist: trusty

language: cpp

git:
  depth: 3

branches:
  only:
  - master
  - travis-macos-build
  - dev

matrix:
  include:
    - os: linux
      services:
        - docker
      before_install:
        - docker pull ethiy/proj.city
      script:
        - docker run ethiy/proj.city /bin/sh -c "export CC=/usr/bin/gcc; export CXX=/usr/bin/g++; cmake ../.. -DCGAL_DIR=/usr/lib/x86_64-linux-gnu/CGAL/; cmake ../..; make -j4"

    - os: linux
      services:
        - docker
      before_install:
        - docker pull ethiy/proj.city
      script:
        - docker run ethiy/proj.city /bin/sh -c "export CC=/usr/bin/clang; export CXX=/usr/bin/clang++; cmake ../.. -DCGAL_DIR=/usr/lib/x86_64-linux-gnu/CGAL/; cmake ../..; make -j4"
