sudo: required
dist: trusty

language: cpp

git:
  depth: 3

branches:
    only:
    - master
    - travis-macos-build
    - dev

os: osx
osx_image: xcode8
cache:
  directories:
    - $HOME/Library/Caches/Homebrew
    - ./external
    - $HOME/3rdParty
compiler: clang
before_install:
  - brew update
  - brew outdated boost || brew upgrade boost
  - brew install lib3ds
  - brew install tinyxml2
  - brew tap osgeo/osgeo4mac && brew tap --repair
  - brew install jasper netcdf readline sqlite libxml2 liblwgeom webp cfitsio popt epsilon openssl libdap little-cms2 openjpeg unixodbc xerces-c xz
  - mkdir -p 3rdParty && cd 3rdParty
  - wget https://github.com/CGAL/cgal/archive/releases/CGAL-4.10.tar.gz
  - mkdir CGAL-4.10 && tar xf CGAL-4.10.tar.gz -C CGAL-4.10 --strip-components 1 && cd CGAL-4.10
  - mkdir build && cd build
  - cmake ..
  - sudo make -j `nproc` install && sudo make install_FindCGAL
  - cd $TRAVIS_BUILD_DIR/3rdParty
  - wget http://download.osgeo.org/gdal/2.1.3/gdal-2.1.3.tar.gz
  - mkdir gdal-2.1.3 && tar xf gdal-2.1.3.tar.gz -C gdal-2.1.3 --strip-components 1 && cd gdal-2.1.3
  - mv ../../ressources/patch_gdal-2.1.3/jpeg2000_vsil_io.patch ./frmts/jpeg2000/jpeg2000_vsil_io.patch
  - cd ./frmts/jpeg2000 && patch < jpeg2000_vsil_io.patch && cd -
  - ./configure
  - make -j4 && make install
  - cd $TRAVIS_BUILD_DIR
  - mkdir build
  - mkdir build/darwin
install:
  - cd build/darwin
  - cmake -DCGAL_DONT_OVERRIDE_CMAKE_FLAGS=ON ../..
script:
  - make -j4 all
