sudo: required

language: cpp

git:
    depth: 3

branches:
    only:
    - master
    - build-system-trial

matrix:
    - os: linux
      services:
        - docker
      script:
        - docker build .

    - os: osx
      osx_image: xcode8
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
          - ./external/Catch/src/Catch-External
      compiler: clang
      before_install:
        - brew update
        - brew outdated boost || brew upgrade boost
        - brew outdated cgal || brew upgrade cgal
        - brew install lib3ds
        - mkdir build
        - mkdir build/darwin
      install:
        - cd build/darwin
        - cmake -DCGAL_DONT_OVERRIDE_CMAKE_FLAGS=ON ../..
      script:
        - make -j4 all
        - ./test_exec -a
