sudo: required
dist: trusty

language: cpp

git:
    depth: 3

branches:
    only:
    - master
    - build-system-trial

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      language: cpp
      sudo: required
      cache:
        apt: true
      before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
        - sudo apt-get update -qq
        - sudo apt-get install -y build-essential g++-4.8 cmake
        - sudo apt-get install -y libboost-filesystem-dev libboost-system-dev libboost-regex-dev lib3ds-dev libtinyxml2-dev libcgal-dev libqt5opengl5-dev libgdal-dev
      script:
        - mkdir -p build && mkdir -p build/trusty && cd build/trusty
        - cmake ../..
        - cmake ../..
        - make -j4
        - ./tests/tests
        - rm *.off *.3ds *.gml *.xsd *.geotiff


    - os: linux
      services:
        - docker
      script:
        - docker build .


    - os: osx
      osx_image: xcode8
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
          - ./external
          - $HOME/3rdParty
      compiler: clang
      before_install:
        - brew update
        - brew outdated boost || brew upgrade boost
        - brew outdated cgal || brew upgrade cgal
        - brew install lib3ds
        - brew install tinyxml2
        - git pull origin build-system-trial
        - mkdir -p 3rdParty && cd 3rdParty
        - mkdir -p GDAL && cd GDAL
        - wget http://www.kyngchaos.com/files/software/frameworks/GDAL_Complete-2.1.dmg
        - sudo hdiutil attach GDAL_Complete-2.1.dmg
        - sudo installer -package "/Volumes/GDAL Complete/GDAL Complete.pkg" -target /
        - cd $TRAVIS_BUILD_DIR
        - mkdir build
        - mkdir build/darwin
      install:
        - cd build/darwin
        - cmake -DCGAL_DONT_OVERRIDE_CMAKE_FLAGS=ON ../..
      script:
        - make -j4 all
        - ./tests/tests
        - rm *.off *.3ds *.gml *.xsd *.geotiff
