version: '{build}'

branches:
  only:
    - master
    - build-system-trial

cache:
  - c:\cygwin-setup-cache

environment:
  CYGWIN_NOWINPATH: yes
  matrix:
    - cygwin_url: https://cygwin.com/setup-x86_64.exe
    - cygwin_url: https://cygwin.com/setup-x86.exe

init:
  - ps: Invoke-WebRequest $env:cygwin_url -OutFile c:\cygwin-setup.exe
  - c:\cygwin-setup.exe --quiet-mode --no-shortcuts --no-startmenu --no-desktop --upgrade-also --only-site --site http://cygwin.mirror.constant.com/ --root c:\cygwin-root --local-package-dir c:\cygwin-setup-cache --packages automake, gcc-g++, make, pkg-config, unzip, wget, curl, zlib-devel,libboost-devel,libmpfr-devel,libgmp-devel
install:
  - c:\cygwin-root\bin\run $APPVEYOR_BUILD_FOLDER\ci\install.sh
before_build:
  - c:\cygwin-root\bin\run $APPVEYOR_BUILD_FOLDER\ci\before_build.sh
build_script:
  - c:\cygwin-root\bin\sh -lc "make -j4 all"

test:
  - c:\cygwin-root\bin\sh -lc ".\test-exec -a"
