version: '0.0.0_{build}'

branches:
  only:
    - build-system-trial

cache:
  - lib3ds-1.3.0
  - lib3ds-1.3.0.zip

install:
  - C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -Syu pacman"
  - C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -S mingw-w64-x86_64-toolchain"
  - C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -S libtool make cmake"
  - C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -S mingw-w64-x86_64-boost"
  - C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -S mingw-w64-x86_64-cgal"
  - appveyor DownloadFile https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/lib3ds/lib3ds-1.3.0.zip
  - 7z x lib3ds-1.3.0.zip
  - C:\msys64\mingw64.exe -lc "export PATH=/mingw64/bin:$PATH; cd /C/projects/3dscenemodel/lib3ds-1.3.0/; ./configure; make -j4; make install"
build_script:
  - ps: New-Item -ItemType Directory -Path .\build\MSYS2
  - C:\msys64\usr\bin\bash.exe -lc "echo PATH=/mingw64/bin:$PATH; cd /C/projects/3dscenemodel/build/MSYS2; cmake -DCGAL_DONT_OVERRIDE_CMAKE_FLAGS=ON ..\.. ; make -j4"
test_script:
  - C:\msys64\usr\bin\bash.exe -lc "export PATH=/mingw64/bin:$PATH; /C/projects/3dscenemodel/build/MSYS2/test_exec -a"
