version: '0.4.1_{build}'

branches:
  only:
    - master
    - dev

install:
  - ps: |
        $local:MsysPath = "C:\msys64\bin;C:\msys64\usr\bin\"
        $local:GitPaths = ""
        foreach($item in ($env:Path.Split(";") | Group-Object { $_.Contains("Git") -or $_.Contains("cygwin") -or $_.Contains("mingw") -or $_.Contains("MinGW") })){
            if($item.Name -eq $true) {
                $local:GitPaths = $item.Group -join ";"
            }
            else {
                $env:Path = $item.Group -join ";"
            }
        }
        foreach($item in @( $local:MsysPath )){
            if(-Not ($env:Path.Split(";") -contains $item)){
                $env:Path = "$env:Path;$item"
            }
        }
  - C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -Syu pacman"
  - C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -S mingw-w64-x86_64-toolchain"
  - C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -S libtool make"
  - C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -S mingw-w64-x86_64-{boost,cmake}"
  - C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -S mingw-w64-x86_64-eigen3"
  - C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -S mingw-w64-x86_64-gmp"
  - C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -S mingw-w64-x86_64-mpfr"
  - C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -S mingw-w64-x86_64-tinyxml2"
  - ps: |
        New-Item -ItemType Directory -Path .\3rParty
        Set-Location 3rParty
  - appveyor DownloadFile https://github.com/CGAL/cgal/archive/releases/CGAL-4.11.1.tar.gz
  - C:\msys64\usr\bin\bash.exe -lc "MSYSTEM=MINGW64 . /etc/profile; cd /C/projects/3dscenemodel/3rParty/; mkdir CGAL-4.11.1 && tar xf CGAL-4.11.1.tar.gz -C CGAL-4.11.1 --strip-components 1"
  - C:\msys64\usr\bin\bash.exe -lc "MSYSTEM=MINGW64 . /etc/profile; cd /C/projects/3dscenemodel/3rParty/CGAL-4.11.1/; mkdir build; cd build; cmake ..; make -j4 install; make install_FindCGAL"
  - appveyor DownloadFile ​http://download.osgeo.org/gdal/2.1.3/gdal213.zip
  - 7z x gdal213.zip
  - C:\msys64\usr\bin\bash.exe -lc "MSYSTEM=MINGW64 . /etc/profile; cd /C/projects/3dscenemodel/3rParty/gdal-2.1.3; ./configure; make -j4; make install"
  - appveyor DownloadFile https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/lib3ds/lib3ds-1.3.0.zip
  - 7z x lib3ds-1.3.0.zip
  - C:\msys64\usr\bin\bash.exe -lc "MSYSTEM=MINGW64 . /etc/profile; cd /C/projects/3dscenemodel/3rParty/lib3ds-1.3.0/; ./configure; make -j4; make install"
build_script:
  - ps: New-Item -ItemType Directory -Path ..\build\MSYS2
  - C:\msys64\usr\bin\bash.exe -lc "MSYSTEM=MINGW64 . /etc/profile; cd /C/projects/3dscenemodel/build/MSYS2; /mingw64/bin/cmake -G'Unix Makefiles' -DCGAL_DONT_OVERRIDE_CMAKE_FLAGS=ON ../.. ; make -j4"

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
