version: '{build}'

branch:
   only:
   - master
   - build-system-trial

image: Visual Studio 2015
os: Visual Studio 2015

environment:
  Configuration: Release
  matrix:
  - TARGET: msvc-2015
    VS: 2015
  - TARGET: msvc-2013
    VS: 2013

platform: x86

init:
  - ps: .\appveyor\init.ps1

before_build:
  - ps: New-Item -ItemType Directory -Path .\build
  - ps: Set-Location build\
  - ps: cmake ..

build:
  - ps: msbuild.exe ALL

test:
  - ps: .\test-exec -a
