version: '0.0.0_{build}'

branches:
  only:
    - master
    - build-system-trial

install:
  - C:\cygwin\bin\sh ./ci/install.sh
before_build:
  - C:\cygwin\bin\sh ./ci/before_build.sh
build_script:
  - C:\cygwin\bin\sh -lc "make -j4 all"

test_script:
  - C:\cygwin\bin\sh -lc ".\test-exec -a"
