version: '0.0.0_{build}'

branches:
  only:
    - build-system-trial

cache:
  - lib3ds-1.3.0
  - lib3ds-1.3.0.zip

install:
  - cmd: echo %PATH%
  - C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -Syu pacman"
  - C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -S mingw-w64-x86_64-toolchain"
  - C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -S libtool make"
  - C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -S mingw-w64-x86_64-boost"
  - C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -S mingw-w64-x86_64-cgal"
  - appveyor DownloadFile https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/lib3ds/lib3ds-1.3.0.zip
  - 7z x lib3ds-1.3.0.zip
  - C:\msys64\usr\bin\bash.exe -lc "cd /C/projects/3dscenemodel/lib3ds-1.3.0/ && ./configure && make -j4 all && make install"
build_script:
  - ps: New-Item -ItemType Directory -Path .\build\MinGW_64
  - ps: Set-Location .\build\MinGW_64\
  - cmake -G"MinGW Makefiles" -DCGAL_DONT_OVERRIDE_CMAKE_FLAGS=ON ..\..
  - C:\msys64\bin\mingw32-make.exe -j4 all
test_script:
  - .\test_exec -a
