version: '0.0.0_{build}'

branches:
  only:
    - master
    - build-system-trial

install:
  - ps: |
        $local:MsysPath = "C:\msys64\bin;C:\msys64\usr\bin\"
        $local:GitPaths = ""
        foreach($item in ($env:Path.Split(";") | Group-Object { $_.Contains("Git") -or $_.Contains("cygwin") -or $_.Contains("mingw") -or $_.Contains("MinGW") })){
            if($item.Name -eq $true) {
                $local:GitPaths = $item.Group -join ";"
            }
            else {
                $env:Path = $item.Group -join ";"
            }
        }
        foreach($item in @( $local:MsysPath )){
            if(-Not ($env:Path.Split(";") -contains $item)){
                $env:Path = "$env:Path;$item"
            }
        }
  - C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -Syu pacman"
  - C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -S mingw-w64-x86_64-toolchain"
  - C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -S libtool make"
  - C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -S mingw-w64-x86_64-{boost,cmake}"
  - C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -S mingw-w64-x86_64-{eigen3,qt5}"
  - C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -S mingw-w64-x86_64-cgal"
  - C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -S mingw-w64-x86_64-gdal"
  - ps: |
        New-Item -ItemType Directory -Path .\3rParty
        Set-Location 3rParty
  - cmd: git clone https://github.com/Ethiy/imagine-pp.git
  - C:\msys64\usr\bin\bash.exe -lc "MSYSTEM=MINGW64 . /etc/profile; cd /C/projects/3dscenemodel/3rParty/imagine-pp; mkdir build; cd build; /mingw64/bin/cmake -G'Unix Makefiles' .. ; make -j4; make install"
  - appveyor DownloadFile https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/lib3ds/lib3ds-1.3.0.zip
  - 7z x lib3ds-1.3.0.zip
  - C:\msys64\usr\bin\bash.exe -lc "MSYSTEM=MINGW64 . /etc/profile; cd /C/projects/3dscenemodel/lib3ds-1.3.0/; ./configure; make -j4; make install"
build_script:
  - ps: New-Item -ItemType Directory -Path ..\build\MSYS2
  - C:\msys64\usr\bin\bash.exe -lc "MSYSTEM=MINGW64 . /etc/profile; cd /C/projects/3dscenemodel/build/MSYS2; /mingw64/bin/cmake -G'Unix Makefiles' -DCGAL_DONT_OVERRIDE_CMAKE_FLAGS=ON ../.. ; make -j4"
test_script:
  - IF NOT "%APPVEYOR_REPO_BRANCH%" == "master" C:\msys64\usr\bin\bash.exe -lc "MSYSTEM=MINGW64 . /etc/profile; cd /C/projects/3dscenemodel/build/MSYS2; ./tests -a"
