version: '0.0.0_{build}'

branches:
  only:
    - build-system-trial

install:
  - C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -Syu pacman"
  - C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -S mingw-w64-x86_64-toolchain"
  - C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -S base-devel"
  - C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -S mingw-w64-x86_64-boost"
  - C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -S mingw-w64-x86_64-cgal"
  - C:\msys64\usr\bin\bash.exe -lc .\ci\install.sh
build_script:
  - ps: New-Item -ItemType Directory -Path .\build\MinGW_64
  - ps: Set-Location .\build\MinGW_64\
  - cmake -G"MinGW Makefiles" -DCGAL_DONT_OVERRIDE_CMAKE_FLAGS=ON ..\..
  - C:\msys64\bin\mingw32-make.exe -j4 all
test_script:
  - .\test_exec -a
